name: GMKoopman
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3
  - python=3.10.4
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - alabaster==0.7.13
      - alembic==1.12.1
      - asttokens==2.4.1
      - attrs==23.1.0
      - babel==2.13.1
      - blinker==1.7.0
      - casadi==3.6.4
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - clarabel==0.6.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - comm==0.2.0
      - contourpy==1.2.0
      - cvxpy==1.4.1
      - cvxpylayers==0.1.6
      - cycler==0.12.1
      - data==0.4
      - databricks-cli==0.18.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - diffcp==1.0.23
      - dill==0.3.7
      - docker==6.1.3
      - docutils==0.18.1
      - ecos==2.0.12
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - filelock==3.13.1
      - flask==2.3.3
      - fonttools==4.44.3
      - fsspec==2023.10.0
      - funcsigs==1.0.2
      - future==0.18.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - greenlet==3.0.1
      - gunicorn==20.1.0
      - hypothesis==6.89.0
      - idna==3.4
      - imageio==2.32.0
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - iniconfig==2.0.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - kiwisolver==1.4.5
      - latex==0.7.0
      - llvmlite==0.41.1
      - mako==1.3.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mlflow==2.5.0
      - mpmath==1.3.0
      - nest-asyncio==1.5.8
      - networkx==3.0
      - neuromancer==1.4.2
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - osqp==0.6.3
      - packaging==23.2
      - pandas==2.1.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pillow==10.0.1
      - platformdirs==4.0.0
      - pluggy==1.3.0
      - plum-dispatch==1.7.3
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.1
      - pybind11==2.11.1
      - pydot==1.4.2
      - pygments==2.17.1
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - python-graphviz==0.20.1
      - pyts==0.13.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qdldl==0.1.7.post0
      - querystring-parser==1.2.4
      - requests==2.31.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - scs==3.2.4
      - seaborn==0.13.1
      - shutilwhich==1.1.0
      - six==1.16.0
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - sphinx==7.2.6
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - sqlalchemy==2.0.23
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tempdir==0.7.1
      - threadpoolctl==3.2.0
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.1.1
      - torchdiffeq==0.2.3
      - tornado==6.3.3
      - traitlets==5.13.0
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - wcwidth==0.2.10
      - websocket-client==1.6.4
      - werkzeug==3.0.1
      - zipp==3.17.0
